### ISSUE TITLE
Debugging grading code

### ISSUE THREAD

**Issue by dtkaplan** [rstudio-education/gradethis#112]
@garrettgman As I'm using `{gradethis}`, I get some unexpected results. For interest, any exercise chunk where the submitted code is a simple assignment leads to a yellow box with a message:

> Last value being used to check answer is invisible. See `?invisible` for more information

I'm trying to get inside the `{gradethis}` code by inserting `browser()` or using the debugger and rebuilding the package. No luck -- the `browser()` or debugging breakpoints are just skipped over. (I can put `cat()` messages into the code successfully, but this is a pretty poor way of learning how the code is working.)

Could you describe how you debug the `{gradethis}` code?

**Comment by chendaniely** [comment]
@dtkaplan Are you using `gradethis` on its own? or within a `learnr` document?

**Comment by dtkaplan** [comment]
Within a learnr document. That said, I’ve also been using some customizations to learnr that provide an alternative route to evaluate code submissions.

**Comment by chendaniely** [comment]
within `learnr` your only hope is really `cat` and `print`. That's because of all the message passing from `learnr` (shiny) to `rmarkdown` to `learnr` garbles a lot of things.

If you're just sticking within `gradethis` you can but in a `browser()` call + rebuild the package and then directly run the `gradethis` functions call in "standalone" mode:

See this vignette (not yet merged yet): https://github.com/rstudio-education/gradethis/blob/vignettes2/vignettes/a-000-introduction_to_gradethis.Rmd

You can also see this slide (and the next one) on how to use `gradethis`: https://speakerdeck.com/chendaniely/satrday-grading-code-with-gradethis?slide=29

I've also put in browser calls in `gradethis` and run the unittests

**Comment by gadenbuie** [comment]
The reason `browser()` calls are skipped when running the tutorial is because they are run in a background, non-interactive session by default. The way around this is to run your tutorial from an interactive console using `rmarkdown::run("path/to/tutorial.Rmd")`. When called in this way, `browser()` statements inside grading code will generally work:

```r
grade_result(
  fail_if(function(x) browser())
)
```

or

```{r}
grade_this(browser())
```

**Comment by joeflack4** [comment]
@gadenbuie Thanks. I was running a `learnr` app and was able to get `browser()` to work by running via `rmarkdown::run()` rather than using RStudio's "Run Document" button.
