### ISSUE TITLE
insert_exercise_grade_code not found

### ISSUE THREAD

**Issue by dominicwhite** [rstudio-education/gradethis#120]
When I try to run "Insert exercise: grade result/conditions" from the Addins menu in RStudio, I get a pop-up dialog with this error:

> no function 'insert_exercise_grade_result_conditions' found in package 'gradethis'

A quick search of the codebase on GitHub suggests that the necessary function is missing.

("Insert exercise: grade code" works just fine, however)

**Comment by gadenbuie** [comment]
Thanks for letting us know! We're going to deprecate the addins (#196) since they don't seem to be a good fit for this package. You can accomplish the same task with [snippets](https://rstudio.github.io/rstudio-extensions/rstudio_snippets.html). Here are [a few examples of learnr snippets](https://github.com/gadenbuie/snippets/blob/03434c07b28658a50adfdb41e790a5e35db20dec/markdown.snippets#L149-L151) that I use.
