### ISSUE TITLE
Deprecate RStudio Addins

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#196]
The RStudio addins `insert_exercise_grade_result()` and `insert_exercise_grade_code()` are out of date and rather than maintain these I think we should deprecate them. RStudio snippets are a better solution since they are easier to customize and allow users to walk through defined fields rather than using a random chunk ID. We can include a set of snippets in the package documentation.

**Comment by chendaniely** [comment]
There were a few reasons why I went for addin:

1. users are more likely to see that an addin exists since it's pominent in the rstudio ide
2. the addin allows for a random chunk name instead of forcing the user to come up with a unique name everytime they need a chunk

For number 2: I'm not sure how many people label all their chunks in an Rmd document, but I almost rarely do. The only real times I name a chunk is if I need to reference it somehow in the rest of the document. I'm not too familiar with the snippets (since I never use them) but iirc it only lets you jump from place holder to place holder, but it does not fill them in with any defualt value.

**Comment by gadenbuie** [comment]
@chendaniely The addin definitely solves a familiar pain point, but I think snippets are a good compromise. I'll make sure they make it into the documentation.

Here's a snippet I use frequently:

````
snippet lrne
	```{r ${1:exercise-name}, exercise = TRUE}
	${2:exercise_code}
	```

	```{r ${1:exercise-name}-hint}
	# hint code
	```

	```{r ${1:exercise-name}-solution}
	${2:exercise_code}
	```

	```{r ${1:exercise-name}-check}
	grade_this_code()
	```
````

You're right that there isn't a good solution for creating a random ID for each exercise chunk — even though snippets _can_ evaluate R code it's still probably not possible to use the same random ID for each code chunk. https://rstudio.github.io/rstudio-extensions/rstudio_snippets.html#executing-r-code
