### ISSUE TITLE
grade_this() documentation and if statements

### ISSUE THREAD

**Issue by ericemc3** [rstudio-education/gradethis#198]
on https://rstudio-education.github.io/gradethis/reference/graded.html
i can read:

`To generate programmatic grades, use graded() or if statements around pass*() and fail*()`

Could you please provide some examples with such if statements?

**Comment by gadenbuie** [comment]
Hi @ericemc3, improved documentation of gradethis is a high priority in the near future.

To clarify the help documentation, the new `grade_this()` function operates slightly differently from the previous `grade_result()` and `grade_code()` functions. In a nutshell, for an exercise labelled `example`, you would write a `-check` chunk that follows this pattern:

````markdown
```{r example-check}
grade_this({
  # ... R code to check the answer ...
  if (the_answer_passes) {
    pass("Feedback message for correct answer")
  }
  if (the_answer_fails) {
    fail("Feedback message for incorrect answer")
  }

  # default to fail() or pass() by calling one of these last
  fail("Not quite")
})
```
````

Because the grade checking code is inside `{...}` you can write checking codes as complicated as you want. You can think of `pass()` and `fail()` like the `return()` function, except that in this case they will indicate if the submitted answer is correct of incorrect. As soon as one of these two functions runs, the checking code stops, so the first one that's called wins. So there's an implied `else` between the two if statements above. 

Note that `the_answer_passes` is a placeholder for a test that you would write. For these tests, you have access to a few special variables that `grade_this()` makes available inside the check block. You can see them listed in the [Check Environment](https://github.com/rstudio-education/gradethis/issues/195#issue-781633396) section in this issue. I think they're also listed in [Available variables](https://rstudio-education.github.io/gradethis/reference/grade_this.html#available-variables) in the `?grade_this` documentation.

In particular, you can reference the result of running the submitted code with `.user` (or `.result`, or `.last_value`, they all reference the same thing). You can also directly inspect the code that was submitted (as a character string) in the variable `.user_code`. If you have a solution chunk for the exercise, the code in that chunk is in `.solution_code` and the last value returned from running that code is available in `.solution`.

Here's a trivial example:

````
```{r example, exercise=TRUE}
# user submits
1 + 3
```

```{r example-solution)
4
```

```{r example-check}
grade_this({
  if (!is.numeric(.user)) {
    fail("Your answer should be numeric.")
  }
  if (.result > 10) {
    fail("Your answer shouldn't be such a big number.")
  }
  if (identical(.user, .solution)) {
    pass("Good job, the answer is 4!")
  }
  fail("That's not the answer I'm looking for, sorry!")
})
```
````

I hope this helps and feel free to write back if you have any questions!

**Comment by ericemc3** [comment]
Hi @gadenbuie,
and thank you very much for that excellent documentation! Your last example is canonical: a succession of fail tests adjusted to guide the user and help him find his way, then a pass, and a final fail for any other case.

Using `.solution` in `grade_this()` refering to an externalized bloc is an elegant way as well to clearly separate the grade logic and the result to compare with.

I am just wondering: why 3 variables for the same thing,  `.user,` `.result` and `.last_value`?

Finally, the 'correct' message is displayed with one extra blank line (tested here with your last example):
![image](https://user-images.githubusercontent.com/17407796/104119341-ef1a2080-532e-11eb-8488-f694f75dcffd.png)

**Comment by gadenbuie** [comment]
I'm glad that was helpful!

> I am just wondering: why 3 variables for the same thing, `.user,` `.result` and `.last_value`?

Partly for convenience, partly for compatibility. learnr uses `.last_value` (well, without the dot) and gradethis previously leaned on `.result` in `grade_result()`. Now with `grade_this()`, we have `.solution` and `.solution_code` available for inspection, in addition to `.user_code`, so `.user` is a natural choice for symmetry... 

> Finally, the 'correct' message is displayed with one extra blank line (tested here with your last example):

Which versions of gradethis, learnr, and rmarkdown are you using? If you could share the results of `devtools::package_info(c("gradethis", "learnr", "rmarkdown"))` that would be helpful. Also, your `setup` chunk might be needed to diagnose.

But most likely is that it's an issue with CSS. There should be a rule like

```css
.alert > p {
  margin-bottom: 0;
}
```

somewhere in the CSS used by the tutorial (it's in the default rmarkdown themes since about 2 years ago). If you're using custom CSS, you might need to add that rule to your stylesheet.

**Comment by ericemc3** [comment]
Thank you for the explanation!
And for directing me to CSS, i had an extra white-space: pre-line, for a reason i have forgotten, causing the extra margin. Sorry for that.
