### ISSUE TITLE
Environment for evaluation of .solution

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#199]
Because `.solution` is delay-assigned, it's possible to pass it on to other functions where it's ultimately evaluated in the wrong environment.

Here's a simple reprex. Submitting the answer returns `object 'x' not found` because `.solution` refers to `x` from the setup chunk.

````markdown
```{r example-setup}
x <- 1
```

```{r example, exercise=TRUE}
# user submits
x + 3
```

```{r example-solution}
x + 3
```

```{r example-check}
grade_this({
  pass_if_equal(.solution)
  fail()
})
```
````

Changing the grading code to the following fixes the issue, but I suspect this won't be obvious and will cause issues down the line, and really this treats the symptom not the problem.

````
```{r example-check}
grade_this({
  pass_if_equal(force(.solution))
  fail()
})
```
````

Here's the kicker, though. I'm fairly certain that the real issue is that `envir_prep` doesn't actually contain the results of the exercise setup chunk, just the global setup chunk.

````
```{r example-check}
grade_this({
  message(str(list(envir_prep = pryr::rls(.envir_prep))))
  pass_if_equal(.solution)
  fail()
})
```
````

Running that through the solution check gives

````
 $ envir_prep:List of 2
  ..$ : chr [1:3] ".server_context" ".shiny_prerendered_server_start_code" "same"
  ..$ : chr [1:4] ".First" ".Random.seed" "dput_to_string" "same"
````

where no `x` is defined. `.envir_prep` should be the same environment where `solution_expr` is evaluated.

https://github.com/rstudio-education/gradethis/blob/a07ecfee1e64578efba35f3aa62744d08806db82/R/grade_learnr.R#L130-L133

**Comment by schloerke** [comment]
Walking through the learnr code... @gadenbuie, you are correct in that `envir_prep` is essentially a copy of the global set chunk. 🤦 This is not expected behavior.

This might be able to be fixed in learnr by doing a 2-stage rmarkdown render. The first render all setup chunks using `envir_prep` and the second part would render the user code using `envir_result`, which would inherit from `envir_prep`.

It might be good to map out how we would like the environments to behave and what restrictions we should have. If we can get rid of `learnr::duplicate_env(x_env)`, I think it would clean up the mental model and be easier to follow.

**Comment by gadenbuie** [comment]
_This is probably a better conversation for learnr, but hey, here we are._

If I understand correctly, the issue is in these lines https://github.com/rstudio/learnr/blob/75e4e70906aecb868fc1d3fdc3ec5af4d60cca64/R/exercise.R#L193-L197

```r
  if (evaluate_global_setup) {
    eval(parse(text = exercise$global_setup), envir = envir)
  }


  envir_prep <- duplicate_env(envir)
```

At this point, `exercise` will have both `$global_setup` and `$setup` items. The first contains the code in the setup chunk and the second contains the concatenated code from walking the setup chunk dependency list.

The problem is that only `global_setup` is evaluated into `envir_prep`, but the setup items are not. AFAICT the global setup code and collated setup code are also not passed on to the checker function:

https://github.com/rstudio/learnr/blob/75e4e70906aecb868fc1d3fdc3ec5af4d60cca64/R/exercise.R#L264-L274

```r
  args <- list(
    label = exercise$label,
    user_code = exercise$code,
    solution_code = exercise$solution,
    check_code = check_code,
    envir_result = envir_result,
    evaluate_result = evaluate_result,
    envir_prep = envir_prep,
    last_value = last_value,
    engine = engine
  )
```

Here are a couple options I see:

1. Evaluate the setup chunks into the `envir` created from `server_envir` [approx here](https://github.com/rstudio/learnr/blob/75e4e70906aecb868fc1d3fdc3ec5af4d60cca64/R/exercise.R#L82-L84). The would match the expectation that `envir` coming into `evaluate_exercise()` is equal to `envir_prep`. But IIUC the `envir` of `evaluate_exercise()` might be supplied elsewhere...
2. Update the `evaluate_global_setup` arg of `evaluate_exercise()` to one of these possible options
	
   - Assume `evaluate_global_setup` means evaluate global setup + setup chunks
   - Add a separate argument `evaluate_chunk_setup` with the default `evaluate_global_setup`
   - Rename `evaluate_global_setup` to `evaluate_setup` but use behavior of first option

   and then we evaluate global and chunk setup code according to that choice.

3. Update the `exercise` object to include `global_setup_code` and `setup_code` which take `exercise$global_setup` and `exercise$setup` respectively.

Some combination of the above would get us to the point where either `envir_prep` contains the environment _just before execution_ of the student code, or let gradethis recreate that environment.

**Comment by schloerke** [comment]
Your understanding is correct, but _evaulating_ must be done using `rmarkdown::render()`.

* If we pass the setup code through, this will encourage double evaluate all exercise setup code. (Not optimal)
* We can't evaluate in the sense of `eval(ex_setup_code, envir = envir_prep)` as it could be python or even mysql code.

So altering option 1...

https://github.com/rstudio/learnr/blob/75e4e70906aecb868fc1d3fdc3ec5af4d60cca64/R/exercise.R#L385-L392 could be split into two `rmarkdown::render()` calls. The first with `envir_prep` and the second with `envir`. It might make more sense to have `render_exercise()` create and return `envir_result`, rather than passing in `envir` (which is treated as `envir_result`).

By having `rmarkdown::render()` in two steps, we can make sure that all code is evaluated with `rmarkdown` (polyglot support) and that `envir_prep` gets evaluated with all exercise setup code.

You are correct in that we might have to move the first part of populating `envir_prep` higher into the execution stack. This would allow for the code checker to have a properly populated `envir_prep` value.
