### ISSUE TITLE
Align .onLoad and gradethis_setup()

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#206]
AFAICT `.onLoad()` does the same work as `gradethis_setup()`, but because some arguments of `gradethis_setup()` differ from the default options in `gradethis_default_options`, these two processes might be at odds with each other.

```r
library(gradethis)
getOption("gradethis.code.incorrect")
#> [1] "{pipe_warning()}{code_feedback()} {random_encouragement()}"
```

``` r
gradethis::gradethis_setup()
#> Loading required package: gradethis
getOption("gradethis.code.incorrect")
#> [1] "{ .message } { random_encouragement() }"
```

I think we should have `gradethis_setup()` operate more like `learnr::tutorial_options()`. So running

```r
library(gradethis)
gradethis_setup()
```

would be equivalent to

```r
library(gradethis)
```

Effectively, `gradethis_setup()` arguments would all default to `NULL`. The function would set non-`NULL` arguments or fill in unset arguments with the default values. Then `gradethis_default_options` becomes the source of truth about the default option values, but we would document all of the options and their meaning in `gradethis_setup()`.

@schloerke the one piece that's confusing me at the moment is why it's necessary for gradethis to set knitr options in `.onload()` rather than settings the `learnr::tutorial_options()` as in `gradethis_setup()`?

**Comment by schloerke** [comment]
I agree that the args should match. Having `gradethis_setup()` args default to `NULL` sounds good to me as long as the default behavior is documented/mentioned somewhere.

-------------------

I think we did it because it is **REALLY** confusing when you don't call `gradethis_setup()` and no `gradethis` hooks are ever added. So if the package is at least loaded, then it _should_ semi-work. If you never call `gradethis_setup()` and the knitr hooks are not there, it is a big headache to debug what actually is wrong.

If we make everything the same, then maybe `gradethis_setup()` is no longer required? It would only be to change the default behavior? That seems nice!
