### ISSUE TITLE
Tab doesn’t work  when name on it has an accent on it 

### ISSUE THREAD

**Issue by andreavargasmontero** [rstudio-education/gradethis#88]
I'm using `gradethis` to make R tutorials but I'm from Costa Rica, therefore, my tutorials are in spanish. I noticed that when you try to create a tab with an accented word on it, it doesn't work. What I mean is that when you click on it, nothing happens. 

For example:

```
.## Datos: **vowels**

.Este es un set de datos que contiene datos sobre la frecuencia del uso de las vocales en español de participantes un estudio en 1985. Contiene 750 observaciones y 4 variables. 
.```{r}
glimpse(spanish_vowels)
.```

.## Características 

.Descripción de las variables:

.| Variable | Descripcion |
.|:--------:|:-----------:|
.| `label` | Código del participante | 
.| `rep` | Repeitición |
.| `f1`| Vector numérico indicando la vocal F1 en Hz  | "
 
```

When you click the "Características" tab nothing happens, it stays on the "Datos" tab

**Comment by schloerke** [comment]
I believe this is the same issue https://github.com/rstudio/learnr/issues/319 which was fixed in https://github.com/rstudio/learnr/pull/330. 

Please update to the latest `learnr` version (v0.10.1) and restart your R session before trying again.

I'm going to close for now, but if this is still an issue, please comment again with your `sessioninfo::session_info()` and the full tutorial file.  Thank you!
